config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get 'listings', to: 'listings#index'
  get 'listings/under100', to: 'listings#under100', as: 'listings_under_100'
  get 'listings/pet_friendly', to: 'listings#pet_friendly', as: 'listings_pet_friendly'
  get 'listings/family', to: 'listings#family', as: 'listings_family'
  get 'listings/fortwo', to: 'listings#fortwo', as: 'listings_fortwo'
  get 'listings/wifi', to: 'listings#wifi', as: 'listings_wifi'
  get 'listings/kitchen_bbq', to: 'listings#kitchen_bbq', as: 'listings_kitchen_bbq'
  get 'listings/shower_bathroom', to: 'listings#shower_bathroom', as: 'listings_shower_bathroom'
  get 'listings/luxury', to: 'listings#luxury', as: 'listings_luxury'
  get 'listings/new', to: 'listings#new'
  get 'listings/my_listings', to: 'listings#mine', as: 'my_listings'
  get 'listings/my_bookings', to: 'bookings#mine', as: 'my_bookings'
  post 'listings', to: 'listings#create'
  get 'listings/:id', to: 'listings#show', as: 'listing'
  get 'listings/:id/reviews', to: 'reviews#index', as: 'listing_reviews'
  get 'listings/:id/reviews/new', to: 'reviews#new', as: 'new_listing_review'
  post 'listings/:id/reviews', to: 'reviews#create', as: 'create_reviews'
  get 'listings/:id/edit', to: 'listings#edit', as: 'listing_edit'
  patch 'listings/:id', to: 'listings#update'
  delete 'listings/:id', to: 'listings#destroy'
  get 'listings/:id/bookings', to: 'bookings#index', as: 'all_bookings'
  get 'listings/:id/bookings/new', to: 'bookings#new', as: 'bookings'
  post 'listings/:id/bookings', to: 'bookings#create', as: 'listing_bookings'
  delete 'listings/:id/bookings', to: 'bookings#destroy', as: 'delete_bookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_many :availability, dependent: :destroy

  #enable @book.reviews
  has_many :reviews, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :booking, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_one_attached :photo
  #reviews
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  # @review.booking
  validates :content, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :booking
  has_many :listing, through: :booking
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @user = current_user
    @listing = Listing.find(params[:id])
    @booking = Booking.new
    @booking.listing = @listing
    @availability = Availability.where(booking_id: @booking)
  end

  def index
    @bookings = Booking.where(listing: @listing)
    @listing = Listing.find(params[:id])
  end


  def create
    @listing = Listing.find(params[:id])
    @booking_date = booking_params[:booking_date]
    p @blocked_dates = convert_range_to_array(@booking_date)
    @blocked_dates.each do |date|
      @booking = Booking.create(user_id: current_user.id, listing: @listing, booking_date: date)
      @availabilities = Availability.create(available: false, date: date, booking_id: @booking.id, listing_id: @booking.listing_id)
    end
    redirect_to listing_path(@listing), notice: "🎉 Successfully created booking 🎉"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @listing = Listing.find(@booking.listing_id)
    @booking.destroy
    redirect_back(fallback_location: root_path)
  end

  def mine
    @user = current_user
    @bookings = Booking.where(user_id: @user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :listing_id, :booking_date)
  end

  def convert_range_to_array(str)
    if str == ""
      return ""
    else
      a = str.split(" to ")
      a.map { |date| date.to_date }
      (a[0]..a[1]).to_a
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all

    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {listing: listing})
      }
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    # create new listing
    @listing = Listing.new(listing_params)
    # get params
    if @listing.save
      redirect_to listing_path(@listing), notice: "You've successfully created a new listing for your Van 🚗 "
    end
    # redirect to new listing page
    #
  end

  def show
    @listing = Listing.find(params[:id])
    @review = Review.new
    # @booking = Booking.where(listing_id: @listing.id)
    @booking = Booking.new
    @markers = [
      build_listing_object(@listing)
    ]
    @center = [ @listing.longitude, @listing.latitude ]
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path
  end

  def mine
    @listings = Listing.where(user_id: current_user.id)
  end

  def under100
    @listings = Listing.where("price_per_day < ?", 100)
  end

  def pet_friendly
    @listings = Listing.where(pet_friendly: true)
  end

  def family
    @listings = Listing.where("capacity > ?", 2)
  end

  def fortwo
    @listings = Listing.where(capacity: 2)
  end

  def wifi
    @listings = Listing.where(wifi: true)
  end

  def kitchen_bbq
    @listings = Listing.where(kitchen: true).or(Listing.where(bbq: true))
  end

  def shower_bathroom
    @listings = Listing.where(shower: true).or(Listing.where(bathroom: true))
  end

  def luxury
    @listings = Listing.where(luxury: true)
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
    @user = User
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :price_per_day, :photo, :capacity, :user_id, :address,
                                    :pet_friendly, :luxury, :wifi, :bbq, :kitchen, :bathroom, :shower, :tv, :airconditioning, :heating)
  end

  def build_listing_object(listing)
    {
      marker_html: render_to_string(partial: "marker"),
      info_window_html: render_to_string(partial: "info_window", locals: {listing: listing}),
      lat: listing.latitude,
      lng: listing.longitude
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_listing, only: [ :index, :new, :create ]

  def new
    @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    @listing = Listing.find(params[:id])
    @review = Review.new(review_params)
    # @review.listing = @listing
    if @review.save
      redirect_to listing_path(@listing), notice: "🎉 Successfully created review 🎉"
    else
      render "listings/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :listing_id, :user_id)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<head>
  <%= stylesheet_link_tag 'mine' %>
</head>

<div class="container">
  <br>
  <h1 class="my-header"> All bookings <h1>
  <%= link_to 'Back to listing', listing_path(@listing), class: 'btn' %>
  <% @bookings.each do |booking| %>
    <div class="card-product">
    <% if Listing.find(booking.listing_id).photo.attached? %>
      <%= cl_image_tag Listing.find(booking.listing_id).photo.key, width: 400, height: 300, crop: :fit %>
    <% end %>
      <div class="container">
        <div class="card-product-infos">
          <div style="display: flex; justify-content: space-between; ">
            <h3><%= Listing.find(booking.listing_id).title %></h3>
            <%= link_to delete_bookings_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, remote: true, class: 'button button--delete' do %>
              <i class="fa-solid fa-trash" style="color: black"></i>
            <% end %>
          </div>
          <div style="display: flex; justify-content: space-between; ">
            <p><%= booking.booking_date %></p>
            <p><%= booking.user.email %></p>
            <p>$<%= Listing.find(booking.listing_id).price_per_day %>0 AUD/day</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/mine.html.erb
<head>
  <%= stylesheet_link_tag 'mine' %>
</head>

<div class="container">
  <br>
  <div>
  <h1 class="my-header">My bookings</h1>
  <%= @user.email %>
  </div>
  <br>
  <% @bookings.each do |booking| %>
    <div class="card-product">
    <% if Listing.find(booking.listing_id).photo.attached? %>
      <%= cl_image_tag Listing.find(booking.listing_id).photo.key, width: 400, height: 300, crop: :fit %>
    <% end %>
      <div class="container">
        <div class="card-product-infos">
          <div style="display: flex; justify-content: space-between; ">
            <%= link_to listing_path(Listing.find(booking.listing_id)) do %>
              <h3><%= Listing.find(booking.listing_id).title %></h3>
            <% end %>
            <%= link_to delete_bookings_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, remote: true, class: 'button button--delete' do %>
              <i class="fa-solid fa-trash" style="color: black"></i>
            <% end %>
          </div>
          <div style="display: flex; justify-content: space-between; ">
            <p><%= booking.booking_date %></p>
            <p>$<%= Listing.find(booking.listing_id).price_per_day %> AUD/day</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="listing book-listing" style="margin-top: 50px;">
  <div class="container" style="display: flex">
    <div class="col">
        <div class="listing__header" style="text-align: left">
          <h1 class="listing__title">Booking Page for <%= @listing.title %></h1>
          <p class="listing__location">$<%= @listing.price_per_day %> AUD/day</p>
          <%= link_to 'Back to listing', listing_path(@listing) %>
        </div>

        <% if @listing.photo.key? %>
          <%= cl_image_tag @listing.photo.key, width: 400, height: 300, crop: :lfill, class: 'book-img' %>
        <% end %>
    </div>
    <div class="col">
      <%= simple_form_for [@listing, @booking] do |f| %>
        <%=f.hidden_field :user_id, :value => current_user.id %>
        <%=f.hidden_field :listing_id, :value => @listing.id %>
        <%= f.text_field :booking_date,
          data: {
            controller: "flatpickr",
            flatpickr_disabled_dates_value: @listing.availabilities.where(available: false).map{|avail| avail.date.to_s}
          } %>
        <%= f.submit class:'book-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vincent Van-Go</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <!-- MAPBOX LINK -->
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/confetti.css">
    <script src="https://kit.fontawesome.com/fa996264e6.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="content-wrapper">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
      <% if user_signed_in? %>
      <% end %>
      <%= render "shared/footer" %>
    </div>

  </body>
</html>

app/views/listings/_cards.html.erb
<div class="category-section">
  <div class="cards">
    <%= link_to listings_family_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1561361513-2d000a50f0dc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1776&q=80" alt="">
        <h3 class="card-title">Family</h3>
      </div>
    <% end %>
    <%= link_to listings_fortwo_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1519981337-7295e387c157?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="">
        <h3 class="card-title">Just for two</h3>
      </div>
    <% end %>
    <%= link_to listings_pet_friendly_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1507682520764-93440a60e9b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80" alt="">
        <h3 class="card-title">Pet friendly</h3>
      </div>
    <% end %>
    <%= link_to listings_under_100_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1660894990762-0bd08036aa35?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80" alt="">
        <h3 class="card-title">Under $100</h3>
      </div>
    <% end %>
    <%= link_to listings_wifi_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1721&q=80" alt="">
        <h3 class="card-title">Wi-fi</h3>
      </div>
    <% end %>
    <%= link_to listings_kitchen_bbq_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1667574308329-9a986bf1f028?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="">
        <h3 class="card-title">Cooking</h3>
      </div>
    <% end %>
    <%= link_to listings_shower_bathroom_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1563783850023-077d97825802?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="">
        <h3 class="card-title">Bathrooms</h3>
      </div>
    <% end %>
    <%= link_to listings_luxury_path do %>
      <div class="card">
        <img src="https://images.unsplash.com/photo-1515172128886-07c606bb4eb3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2226&q=80" alt="">
        <h3 class="card-title">✨ Luxury</h3>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/_form.html.erb
  <%= simple_form_for(@listing, :html => { :class => 'form-horizontal' }) do |f| %>
    <div class="form-inputs">
      <%= f.input :title, placeholder: 'Caravan' %>
      <%= f.input :address, placeholder: 'Suburb' %>
      <%= f.input :description, placeholder: 'Two beds, kitchen, bath and fridge'%>
      <%= f.input :price_per_day, placeholder: '$' %>
      <%= f.input :capacity, placeholder: 'Number of guests' %>
      <br>
      <%= f.label :extra_features, class: 'extra-features' %>
      <%= f.input :pet_friendly, as: :boolean %>
      <%= f.input :luxury, as: :boolean %>
      <%= f.input :wifi, as: :boolean %>
      <%= f.input :bbq, as: :boolean %>
      <%= f.input :kitchen, as: :boolean %>
      <%= f.input :bathroom, as: :boolean %>
      <%= f.input :shower, as: :boolean %>
      <%= f.input :tv, as: :boolean %>
      <%= f.input :airconditioning, as: :boolean %>
      <%= f.input :heating, as: :boolean %>
      <br>
      <%= f.input :photo, as: :file %>
      <%=f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit class: 'btn' %>
    </div>
  <% end %>

app/views/listings/family.html.erb
<%= render "listings" %>

app/views/listings/fortwo.html.erb
<%= render "listings" %>

app/views/listings/index.html.erb
<div class="container">
  <%= link_to 'Create new listing', new_listing_path, class: 'btn' %>
  <div class="cards">
      <% @listings.each do |item| %>
        <%= link_to listing_path(item.id), class: "card" do %>
          <% if item.photo.attached? %>
            <%= cl_image_tag(item.photo.key, width: 400, height: 300, crop: :lfill) %>
          <% else %>
            <img src="https://images.pexels.com/photos/5763198/pexels-photo-5763198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="">
          <% end %>
          <h4 class="listing-title truncate"><%= item.title %></h4>
          <p class="price">$<%= item.price_per_day %> <small>AUD/day</small> </p>
        <% end %>
      <% end %>
  </div>
</div>

app/views/listings/kitchen_bbq.html.erb
<%= render "listings" %>

app/views/listings/luxury.html.erb
<%= render "listings" %>

app/views/listings/mine.html.erb
<div class="container">

  <br>
  <h1 style="margin-top: 10px" class="my-header">My Listings</h1>
  <%= link_to 'Create new listing', listings_new_path, class: 'btn' %>
  <div class="cards">
      <% @listings.each do |item| %>
        <%= link_to listing_path(item.id), class: "card" do %>
          <% if item.photo.attached? %>
            <%= cl_image_tag(item.photo.key, width: 400, height: 300, crop: :lfill) %>
          <% else %>
            <img src="https://images.pexels.com/photos/5763198/pexels-photo-5763198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="">
          <% end %>
          <h4 class="listing-title truncate"><%= item.title %></h4>
          <p class="price">$<%= item.price_per_day %> <small>AUD/day</small> </p>
          <%# <%= link_to 'Delete', listing_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>
      <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1 class="header">Create a new listing<h1>

      <%= render "form", listing: @listing %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<head>
  <%= stylesheet_link_tag 'show' %>
</head>

<div class="flex-container">
  <div class="listing">
    <div class="listing__header">
      <h1 class="listing__title"><%= @listing.title %></h1>
      <p class="listing__location"><%= @listing.title.split(", ").first %></p>
    </div>

    <% if @listing.photo.key? %>
      <%= cl_image_tag @listing.photo.key, width: 400, height: 300, crop: :lfill %>
    <% end %>

    <div class="listing__details">
      <p class="listing__address"><strong>Address:</strong> <%= @listing.address %></p>
      <p class="listing__price"><strong>Price:</strong> <%= number_to_currency(@listing.price_per_day) %> per day</p>
      <p class="listing__user"><strong>Contact:</strong> <%= @listing.user.email %></p>
    </div>

    <div class="listing__description">
      <p><%= @listing.description %></p>
      <p> Comfortably fits <%= @listing.capacity %></p>
    </div>
    <div class="listing__description" style="margin-bottom: 30px">
      <h1>Additional Features:</h1>
        <% if @listing.pet_friendly %>
          <i class="fa-solid fa-paw"></i> Pet Friendly
          <br>
        <% end %>
        <% if @listing.luxury %>
          <i class="fa-solid fa-sack-dollar"></i> Luxury
          <br>
        <% end %>
        <% if @listing.wifi %>
          <i class="fa-solid fa-wifi"></i> Wifi
          <br>
        <% end %>
        <% if @listing.bbq %>
          <i class="fa-solid fa-fire-burner"></i> BBQ
          <br>
        <% end %>
        <% if @listing.kitchen %>
          <i class="fa-solid fa-kitchen-set"></i> Kitchen
          <br>
        <% end %>
        <% if @listing.bathroom %>
          <i class="fa-solid fa-toilet"></i> Bathroom
          <br>
        <% end %>
        <% if @listing.shower %>
          <i class="fa-solid fa-shower"></i> Shower
          <br>
        <% end %>
        <% if @listing.tv %>
          <i class="fa-solid fa-tv"></i> TV
          <br>
        <% end %>
        <% if @listing.airconditioning %>
          <i class="fa-solid fa-snowflake"></i> airconditioning
          <br>
        <% end %>
        <% if @listing.heating %>
          <i class="fa-solid fa-fire"></i> Heating
          <br>
        <% end %>
    </div>

    <div>
      <h1>All Reviews</h1>
      <% if @listing.reviews.blank? %>
        Be the first to leave a review for <%= @listing.title %>
      <% else %>
        <% @listing.reviews.each do |review| %>
          <div style="background-color: #8c8634">
            <p><%= review.content %></p>
            <p>by <%= User.find(review.user_id).email %></p>
          </div>
        <% end %>
      <% end %>
    </div>
    <div style="margin-top: 20px; margin-bottom: 30px;">
      <%= simple_form_for [@listing, @review] do |f| %>
        <%= f.input :content %>
        <%= f.hidden_field :listing_id, :value => @listing.id %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.button :submit %>
      <% end %>
    </div>

    <div class="listing__actions">
      <%= link_to 'Edit', listing_edit_path(@listing), class: 'button button--edit' %>
      <%= link_to 'Delete', listing_path(@listing), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'button button--delete' %>
      <%= link_to 'my bookings',  my_bookings_path %>
      <% if current_user.id == @listing.user_id %><%= link_to 'See Bookings',  all_bookings_path(@listing) %><% end %>
    </div>

  </div>
  <div class="listing booking-card">
      <%= simple_form_for [@listing, @booking] do |f| %>
        <%=f.hidden_field :user_id, :value => current_user.id %>
        <%=f.hidden_field :listing_id, :value => @listing.id %>
        <%= f.text_field :booking_date,
          data: {
            controller: "flatpickr",
            flatpickr_disabled_dates_value: @listing.availabilities.where(available: false).map{|avail| avail.date.to_s}
          } %>
        <%= f.submit class:'book-btn' %>
      <% end %>
      <p>You won't be charged now</p>
  </div>
</div>

<div class="container map-container">
  <h2 class="map-title">Location</h2>
  <div class="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-center-value="<%= @center.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">

  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "Red.png" %>


    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "View Vans", listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List Your Van", listings_new_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Manage my bookings",  my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Manage my listings", my_listings_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "View Vans", listings_path, class: "nav-link" %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>